// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZq46klR-8pUL_FlP5y5YXvwm3ZioByGs',
    appId: '1:729887176928:web:0c30a1ae8595fc4f783885',
    messagingSenderId: '729887176928',
    projectId: 'nexusapp-bdc61',
    authDomain: 'nexusapp-bdc61.firebaseapp.com',
    storageBucket: 'nexusapp-bdc61.appspot.com',
    measurementId: 'G-YLK1C1RNYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBwujITvGJLpZK9RcQu7uMEucESLsZqdg',
    appId: '1:729887176928:android:c44f77073a373d60783885',
    messagingSenderId: '729887176928',
    projectId: 'nexusapp-bdc61',
    storageBucket: 'nexusapp-bdc61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrwp67qcWMz9lZRpFNBha5rGYGthjz_S0',
    appId: '1:729887176928:ios:28ca79aea1f1eec4783885',
    messagingSenderId: '729887176928',
    projectId: 'nexusapp-bdc61',
    storageBucket: 'nexusapp-bdc61.appspot.com',
    iosBundleId: 'com.mehdi.myBooksApp',
  );
}
